// automatically generated by the FlatBuffers compiler, do not modify

package reaktor.sample

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class Color (val value: Byte) {
    companion object {
        val Red = Color(0)
        val Green = Color(1)
        val Blue = Color(2)
        val names : Array<String> = arrayOf("Red", "Green", "Blue")
        fun name(e: Color) : String = names[e.value.toInt()]
    }
}

typealias ColorArray = ByteArray
