// automatically generated by the FlatBuffers compiler, do not modify

package reaktor.sample

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class Equipment (val value: UByte) {
    companion object {
        val None = Equipment(0u)
        val Weapon = Equipment(1u)
        val names : Array<String> = arrayOf("NONE", "Weapon")
        fun name(e: Equipment) : String = names[e.value.toInt()]
    }
}

typealias EquipmentArray = UByteArray
